languages = {
    "ENG": {
        "about_the_country_of_origin": "About the country of origin (production) and the country of the sender",
        "engine_capacity_home_calculator": "Engine Capacity (cm3)",
        "customs_value_of_car": "Customs value of car",
        "Automobile": "Automobile",
        "date_of_issue": "Date of issue",
        "total_customs_payment": "Total customs payments",
        "AUTOMOBILE": "AUTOMOBILE",
        "LightBlue": "LightBlue",
        "FrontWheelDrive": "FrontWheelDrive",
        "Gasoline": "Gasoline",
        "AUTOMATIC": "AUTOMATIC",
        "AutomaticTransmission": "AutomaticTransmission",
        "ECVT AUTOMATIC": "ECVT AUTOMATIC",
        "MANUAL": "MANUAL",
        "ManualTransmission": "ManualTransmission",
        "Unknown": "Unknown",
        "FLEXIBLE FUEL": "FLEXIBLE FUEL",
        "shipping_fee": "Shipping Fee",
        "FlexibleFuel": "FlexibleFuel",
        "GAS": "GAS",
        "Gasoline": "Gasoline",
        "Other": "Other",
        "cost_of_delivery_to_baku": "Cost of Delivery ",
        "Actual": "Actual",
        "NO": "NO",
        "YES": "YES",
        "4x4 w/Front Whl Drv": "4x4 w/Front Whl Drv",
        "4x4 w/Rear Wheel Drv": "4x4 w/Rear Wheel Drv",
        "4X4Drive": "4X4Drive",
        "All wheel drive": "All wheel drive",
        "AllWheelDrive": "AllWheelDrive",
        "Front-wheel Drive": "Front-wheel Drive",
        "FrontWheelDrive": "FrontWheelDrive",
        "RearWheelDrive": "RearWheelDrive",
        "BLACK": "BLACK",
        "BLUE": "BLUE",
        "type_of_vehicle": "Type of vehicle",
        "engine_type": "Engine Type",
        "Burgundy": "Burgundy",
        "detailed_customs_fee_calculator_msg": "For individuals / Calculator-vehicles",
        "detailed_customs_fee_calculator": "Detailed Customs Fee Calculator",
        "Gold": "Gold",
        "customs_fee": "Customs Fee",
        "Gray": "Gray",
        "GREEN": "GREEN",
        "LightBlue": "LightBlue",
        "Maroon": "Maroon",
        "Red": "Red",
        "Silver": "Silver",
        "TAN": "TAN",
        "White": "White",
        "Actual": "Actual",
        "EXEMPT": "EXEMPT",
        "InoperableDigitalDash": "InoperableDigitalDash",
        "NOT ACTUAL": "NOT ACTUAL",
        "NotActual": "NotActual",
        "NotRequired/Exempt": "NotRequired/Exempt",
        "ALL OVER": "ALL OVER",
        "AllOver": "AllOver",
        "Biohazard": "Biohazard",
        "Electrical": "Electrical",
        "EngineDamage": "EngineDamage",
        "Frame": "Frame",
        "FRONT END": "FRONT END",
        "Front&Rear": "Front&Rear",
        "FrontEnd": "FrontEnd",
        "LeftFront": "LeftFront",
        "LeftRear": "LeftRear",
        "LeftSide": "LeftSide",
        "Mechanical": "Mechanical",
        "MINOR DENT/SCRATCHES": "MINOR DENT/SCRATCHES",
        "NORMAL WEAR": "NORMAL WEAR",
        "Rear": "Rear",
        "REAR END": "REAR END",
        "Repossession": "Repossession",
        "RightFront": "RightFront",
        "RightSide": "RightSide",
        "Rollover": "Rollover",
        "SIDE": "SIDE",
        "Unknown": "Unknown",
        "VANDALISM": "VANDALISM",
        "4DOOREXTENDEDCABPICKUP": "4DOOREXTENDEDCABPICKUP",
        "CONVERTIBLE": "CONVERTIBLE",
        "COUPE": "COUPE",
        "CREWPICKUP": "CREWPICKUP",
        "HATCHBACK2DR.": "Hetçbek (2 qapı)",
        "HATCHBACK4DOOR": "Hetçbek (4 qapı)",
        "HATCHBACK4DR.": "HATCHBACK4DR.",
        "ROADSTER": "ROADSTER",
        "SEDAN": "SEDAN",
        "SEDAN4DOOR": "SEDAN4DOOR",
        "SEDAN4DR.": "SEDAN4DR.",
        "SUPERCABPICKUP": "SUPERCABPICKUP",
        "UTILITY": "UTILITY",
        "WAGON4DR.": "WAGON4DR.",
        "search_bar_msg": "Search Vehicles by Make, Model, Lot number",
        "similar_vehicles": "Similar Vehicles",
        "register_now": "Register Now",
        "register_today_and_get_free": "Register today and get Free Membership! It’s fast and easy.",
        "bid": "Bid",
        "sale_location": "Sale Location",
        "sale_information": "Sale Information",
        "details": "Details",
        "watch": "Watch",
        "shipping": "Shipping",
        "vin": "VIN",
        "no_longer_available_for_bidding": "No longer available for bidding",
        "final_price_estimator": "Final Price Estimator",
        "title_code": "Title Code",
        "odometer": "Odometer",
        "starting_bid_increment": "Starting Bid ($175 USD increment)",
        "maximum_bid_increment": "Maximum Bid ($25 USD increment)",
        "auction_highlights": "Auction Highlights",
        "primary_damage": "Primary Damage",
        "secondary_damage": "Secondary Damage",
        "body_style": "Body Style",
        "vehicle_type": "Vehicle Type",
        "color": "Color",
        "engine": "Engine",
        "damage_type": "Damage Type",
        "cylinders": "Cylinders",
        "transmission": "Transmission",
        "drive": "Drive",
        "fuel": "Fuel",
        "keys": "Keys",
        "special_note": "Special Note",
        "lot": "Lot",
        "bid_information": "Bid Information",
        "bid_status": "Bid Status",
        "recommended_bid": "Recommended Bid",
        "current_bid": "Current Bid",
        "seller_reserve": "Seller Reserve",
        "time_left": "Time Left",
        "rentals": "Rentals",
        "final_bid": "Final Bid At Auction",
        "auction_fee": "Auction Fee",
        "insurance_fee": "Insurance Fee",
        "service_fee": "Service Fee",
        "transfer_fee": "Transfer Fee",
        "documentation_fee": "Documentation Fee",
        "enter_bid": "Enter Your Bid",
        "auction": "Auction",
        "from_country": "From Country",
        "from_port": "From Port",
        "to_country": "To Country",
        "azerbaijan": "Azerbaijan",
        "georgia": "Georgia",
        "to_port": "To Port",
        "location": "Location",
        "sale_date": "Sale Date",
        "sale_status": "Sale Status",
        "sale_name": "Sale Name",
        "lane": "Lane",
        "item": "Item",
        "grid": "Grid",
        "row": "Row",
        "hybrid": "Hybrid",
        "exotic": "Exotic",
        "last_updated": "Last Updated",
        "show_more": "Show More",
        "show_less": "Show Less",
        "view_vehicle": "View Vehicle",
        "final_price": "Final Price",
        "view_full_auto_auction_inventory": "View Full Auto Auction Inventory",
        "popular_makes": "Popular Makes",
        "quick_registration": "Quick Registration – Register for FREE in less than 30 seconds",

        "access_to_over_182": "Access To Over 182 594 Vehicles Without a License",
        "best_prices": "Get The Best Prices Across All Auto Auctions Located In USA",
        "easy_Bidding_buying_shipping": "Easy Bidding, Buying and Shipping Services",
        "customer_satisfaction_rate": "96% Customer Satisfaction Rate",
        "browse_popular": "Browse Popular Vehicles in Azerbaijan",
        "choose_from_over": "Choose from over 181 745 used Cars, Trucks and SUVs",
        "find_your_next_auction": "Order your car from the USA to Azerbaijan",
        "how_to_buy_and_ship_your_vehicle": "How to Buy and Ship Your Vehicle to Azerbaijan",
        "day": "Day",
        "register_with_us": "Register with us",
        "sign_a_contract": "Sign a contract and place a deposit",
        "find_your_vehicle_at_auction": "Find your vehicle at auction",
        "bidding_at_auction": "Bidding at auction",
        "shipping_to": "Shipping to ",
        "payment_for_auction": "Payment for your vehicle",
        "ground_shipping": "Ground Shipping to Azerbaijan",
        "ocean_shipping_to": "Ocean Shipping to Azerbaijan",
        "customs_clearance": "Customs clearance",
        "benefits_of_choosing": "Benefits of Choosing Auto Trader",
        "official_representative": "Official Representative",
        "official_representative_msg": "Auto Trader is the only Official Authorized Copart Online Auctions Platform in Azerbaijan",
        "live_bidding": "Live Bidding",
        "live_bidding_msg": "Place your bids yourself, avoiding intermediaries and overpayments! With our license, you can buy a car from any state without restrictions.",
        "low_transaction_fee": "Low Transaction Fee",
        "low_transaction_fee_msg": "The lowest auction and transaction fees on the market. Price includes consultations with company auction experts.",
        "online_platform": "Online platform",
        "online_platform_msg": "You can control all stages of online purchase, and independently take part in auctions for any car, no hidden fees.",
        "customer_support": "Customer Support",
        "customer_support_msg": "Our team will provide full consultations for customers by telephone for purchases and car delivery.",
        "transportation_to_pak": "Transportation to Azerbaijan",
        "transportation_to_pak_msg": "We have the lowest prices for shipping to Azerbaijan.",
        "payment_calculator": "Payment Calculator",
        "payment_calculator_msg": "Find Out the Final Price for Any Vehicle",
        "get_price_breakdown": "Get a full-price breakdown for your vehicle",
        "get_price_breakdown_msg": "We'll get back to you with final prices, including customs fees and shipping",
        "request_information": "Request Information",
        "check_vin_history": "Check Vin History",
        "check_vin_history_msg1": "ClearVin is a trusted source of vehicle history information and is an approved NMVTIS data provider.",
        "check_vin_history_msg2": "ClearVin reports provide you with thorough vehicle information which including title and brand history, insurance claim information, recall events, loan and retail value and much more.",
        "check_vin_history_msg3": "Buy safely - view detailed information about the car instantly with ClearVin vehicle history reports.",
        "lookup_vin_now": "Lookup VIN Now",
        "enter_17_char_vin_number": "Enter 17 Character VIN Number",
        "where_to_find_vin": "Where to find VIN?",
        "no_vin_click_here": "No VIN? Click here",
        "got_shipping_questions": "Got shipping questions?",
        "got_shipping_questions_msg": "Leave a request to contact a manager",
        "request_callback": "Request a Callback",
        "your_name": "Your Name",
        "international_shipping": "International Shipping – Import cars to Azerbaijan",
        "international_shipping_msg": "We offer competitive shipping services to anywhere in the world. We are a licensed NVOCC and can provide you the best price in the market. Import your next car to Azerbaijan",
        "about_autobidmaster": "About Auto Trader",
        "about_autobidmaster_msg": "With more than 10 years of experience in the automotive industry, we’re here to help you understand the auction process, as well as the best delivery options. We have offices in both the USA and Azerbaijan that work together to get your vehicle to you. Auto Trader is the only Copart Authorized Online Auction Platform in Azerbaijan.",
        "order_shipping": "Order Shipping",
        "delivery_from": "DELIVERY FROM AUCTION TO THE PORT",
        "delivery_from_msg": "Our experts will manage the delivery of your vehicle from the auction location to the port in the US. The transit time depends on the location of the auction yard and destination port.",
        "loading_and_sailing": "LOADING AND SAILING",
        "loading_and_sailing_msg": "We provide shipping services from the USA and Canada. For shipments from the US we use 7 ports: New Jersey, Savannah, Miami, Houston, Los Angeles, Seattle, Chicago.",
        "ocean_sailing_and_unloading": "OCEAN SHIPPING AND UNLOADING",
        "ocean_sailing_and_unloading_msg": "Auto Trader has offices in other countries that are happy to assist you with unloading and customs clearance. We provide you with the final price of your vehicle including shipping cost.",
        "opennig_time": "Opening Hours",
        "your_name": "Your Name",
        "enter_lot_or_vin": "Enter Lot # or VIN",
        "print": "Print",
        "copy": "Copy",
        "shipping_quote": "Shipping Quote",
        "complete_order": "Complete Order",
        "order_placed": "Order Placed",
        "search": "Search",
        "all_makes": "All Makes",
        "all_models": "All Models",
        "all_locations": "All Locations",
        "from_year": "From Year",
        "to_year": "To Year",
        "first_name": "First Name",
        "last_name": "Last Name",
        "email": "Email",
        "by_clicking_you_agree": "By clicking 'REGISTER NOW' you agree to Auto Trader",
        "terms_and_conditions": "Terms and Conditions",
        "already_a_member": "Already a member?",
        "or_continue_with": "OR CONTINUE WITH",
        "continue_with_facebook": "Continue With Facebook",
        "continue_with_google": "Continue With Google",
        "quick_view": "Quick View",
        "sign_in": "Sign In",
        "order_now": "Order Now",
        "phone": "Phone",
        "vehicles_sold_msg": "Vehicles sold 'as is - where is', all sales are final.",
        "want_it_now": "Want It Now?",
        "buy_it_now_price": "Buy It Now Price",

        "more_vin_details": "More Vin Details",
        "vehicle_history": "Vehicle History",
        "get_full_history_report": "Get Full History Report",
        "previous_auction_sales": "Previous Auction Sales",
        "record": "Record",
        "found": "Found",
        "previous_owners": "Previous Owners",
        "title_brand_history": "Title Brand History",
        "lien_impound_theft": "Lien/Impound/Theft",
        "safety_recalls": "Safety Recalls",
        "additional_photos": "Additional Photos",
        "photos": "Photos",
        "clear_vin": "ClearVin",
        "make_offer": "Make Offer",
        "buy_it_now": "Buy It Now",
        "calculate_final_price_for_any_vehicle": "Calculate the Final Price for Any Vehicle",
        "apply_filter": "Apply Filter",
        "filters": "Filters",
        "clear_filter": "Clear All Filter",
        "newly_added_lots": "Newly Added Lots",
        "make": "Make",
        "year": "Year",
        "search_h1": "Online Auto Auction: Salvage, Junk, Damaged, Wrecked Cars for Sale",
        "search_h1_msg": "Welcome to Auto Trader, a place where you can browse, bid on, and buy salvage cars for sale. Available to both public and dealers, our salvage car auctions let you choose from an array of affordable cars with clean and salvage titles. No need to look around for wrecked cars for sale any more. Use our easy-to-use search features to find salvage cars, rebuildable trucks, or repairable cars and bring them home at affordable prices. In fact, most of the wrecked cars for sale listed with are go for as low as less than half their market price. This gives you a great opportunity of owning your dream car. If you do not mind getting your dream car with a few bumps or dents at an affordable price, then you're a step closer to making your dream come true!",
        "search_h2": "How Our Salvage Car Auctions Work",
        "search_h2_msg": "At Auto Trader, we specialize in auto salvage, damaged cars for sale, repairable car, bike and salvage vans, insurance write-offs, ELV's (end of life), MOT failures, faulty and damaged cars and vans; unrecorded accident damaged vehicles and used vehicles. To participate in our salvage car auctions, all you need to do is register with us. Once that is done, you can begin to purchase used cars for sale in the USA, which are usually available only to wholesale, licensed dealers. Our car finder will allow you to see a vast selection of vehicles including trucks, cars, SUVs, boats, tractor trailers, ATVs, motorcycles and so much more. You certainly cannot go wrong when you are purchasing at Auto Trader.",
        "search_h3": "Ready to Find your Preferred Car? Let's Get Started!",
        "search_h3_msg": "Whether you are an individual looking to buy a car for personal use or a dealer looking to add to the inventory, your search for salvage car auctions ends here. If you have any questions or wish to know more about any of the wrecked cars for sale listed with us, please feel free to call us at 1 (503) 298-4300.",
        "salvage_cars_for_sale": "Salvage Cars for Sale",
        "results_found": "Results Found",
        "save_search": "Save Search",
        "save_search_msg": "Press “Save Search” button to save your search here and you will get notified with updates.",
        "saved_search": "Saved Search",
        "image": "Image",
        "electric": "Electric",
        "see_details": "Details",
        "model": "Model",
        "damaged_salvage": "Damaged Salvage",
        "list": "List",
        "address_line": "Heydar Aliyev Ave 115, Sport Plaza Hotel & Apartments 187B",
        "monday": "Monday",
        "friday": "Friday",
        "call_us": "Call Us",
        "text_us": "Text Us",
        "viber": "Viber",
        "whatsapp": "Whatsapp",
        "featured_items": "Featured Items",
        "ownership_doctypes": "Ownership Doc Types",
        "search_by_states": "Search by States",
        "home": "Home",
        "copyright_msg": "Copyright &copy; 2022 Auto Trader, LLC All Rights Reserved. The use of this Web site constitutes acceptance of the Terms of Service and Privacy Policy. Sitemap. Articles. Auto Trader, LLC is not owned by or affiliated with Copart, Inc, or its subsidiaries. All vehicles are purchased from Auto Trader not Copart.",
        "how_to_buy": "How to Buy",
        "find_vehicles": "Find Vehicles",
        "live_auctions": "Live Auctions",
        "shipping": "Shipping",
        "support": "Support",
        "services": "Services",
        "featured_items": "Featured Items",
        "cars_5_years_or_less": "Cars 5 years or less",
        "clean_title": "Clean Title",
        "front_end": "Front End",
        "hail": "Hail",
        "register_to_buy": "Register to Buy",
        "lots_with_bids": "Lots With Bids",
        "new_items": "New Items",
        "no_bids_yet": "No Bids Yet",
        "normal_wear": "Normal Wear",
        "pure_sales_items": "Pure Sales Items",
        "runs_and_drives": "Runs and Drives",
        "salvage_title": "Salvage Title",
        "selling_today": "Selling Today",
        "auction_locations": "Auction Locations",
        "vandalism": "Vandalism",
        "search_auctions": "Search Auctions",
        "flood_damage": "Flood Damage",
        "water_flood": "Water/Flood",
        "no_damage": "No Damage",
        "auctions": "Auctions",
        "rvs": "RVs",
        "company_information": "Company Information",
        "sd": "sd",
        "vehicle_finder": "Vehicle Finder",
        "hail_damage": "Hail Damage",
        "autobidmaster_review": "Auto Trader Review",
        "live_auctions": "Live Auctions",
        "todays_auctions": "Today's Auctions",
        "auction_calendar": "Auction Calendar",
        "join_auctions": "Join Auctions",
        "locations": "Locations",
        "clean_title": "Clean Title ",
        "non_repairable": "Non-repairable ",
        "salvage_title": "Salvage Title ",
        "rejected_repair": "Rejected Repair ",
        "replaced_vin": "Replaced VIN ",
        "rollover": "Rollover ",
        "side": "Side ",
        "stripped": "Stripped ",
        "top_roof": "Top/Roof ",
        "undercarriage": "Undercarriage ",
        "unknown": "Unknown ",
        "vandalism": "Vandalism ",
        "water_flood": "Water/Flood ",
        "all_overs": "All Overs ",
        "biohazard_chemical": "Biohazard/Chemical ",
        "burn": "Burn ",
        "burn___engine": "Burn - Engine ",
        "burn___interio": "Burn - Interior",
        "damage_history": "Damage History ",
        "frame": "Frame ",
        "front_end": "Front End ",
        "hales": "Hales ",
        "mechanical": "Mechanical ",
        "minor_dent_scratches": "Minor Dent/Scratches ",
        "missing_alterd_vin": "Missing/Alterd Vin ",
        "normal_wear": "Normal Wear ",
        "partial_repair_cars": "Partial Repair Cars ",
        "rear_end": "Rear End ",
        "atvs": "ATVs ",
        "boats": "Boats ",
        "cars": "Cars ",
        "classics": "Classics ",
        "dirt_bike": "Dirt Bikes",
        "heavy_duty_trucks": "Heavy Duty Trucks ",
        "industrial_equipment": "Industrial Equipment ",
        "jet_skis": "Jet Skis ",
        "medium_duty_trucks": "Medium Duty Trucks ",
        "motorcycles": "Motorcycles ",
        "pickup_trucks": "Pickup Trucks ",
        "recreational_vehicles": "Recreational Vehicles ",
        "suvs": "SUVs ",
        "sbowmobiles": "Sbowmobiles ",
        "trailers": "Trailers ",
        "convertible": "Convertible ",
        "coupe": "Coupe ",
        "hatchback": "Hatchback ",
        "pickup_trucks": "Pickup Trucks ",
        "seda": "Sedan",
        "suv_crossover": "Suv/Crossover ",
        "vans_minivan": "Vans/Minivan ",
        "wagon": "Wagon ",
        "minor_dent_scratches": "Minor Dent/Scratches",
        "bid_price_2000_or_less": "Bid price $2,000 or less",
        "video_guides": "Video Guides",
        "help_center": "Help Center",
        "rules_and_polices": "Rules and Polices",
        "contact_us": "Contact Us",
        "vehicle_history_report": "Vehicle History Report",
        "domestic_vehicle_transportation": "Domestic Vehicle Transportation",
        "international_shipping": "International Shipping",
        "business_buyers": "Business Buyers",
        "Details": "Details",
        "See Details": "See Details",
        "Results Found": "Results Found",
        "Search Results": "Search Results",
        "Calculator": "Calculator",
        "Other": "Other",
        "DAY": "DAY",
        "Model Group": "Model Group",
        "search_bar": "Search Vehichles by Model Year etc",
        "All Makes": "All Makes",
        "All Models": "All Models",
        "From Year": "From Year",
        "To Year": "To Year",
        "All locations": "All locations",
        "verify-response": "PLEASE CHECK YOUR INBOX TO VERIFY YOUR EMAIL",
        "Met": "Met",
        "Auction Fee": "Auction Fee",
        "Not Yet Met": "Not Yet Met",
        "YOU HAVEN'T BID": "YOU HAVEN'T BID",
        "How to Buy": "How to Buy",
        "Benefits of Choosing Autotrader": "Benefits of Choosing Autotrader",
        "Official representative": "Official representative",
        "Official representative_desc": "Autotrader is the Official Authorized Copart Online Auctions Platform.",
        "Live bidding": "Live bidding",
        "Live bidding_desc": "Place your bids yourself, avoiding intermediaries and overpayments! With our license, you can buy a car from any state without restrictions.",
        "Low Transaction Fees": "Low Transaction Fees",
        "Low Transaction Fees_desc": "The lowest auction and transaction fees on the market. Price includes consultations with company auction experts.",
        "Online platform": "Online platform",
        "Online platform_desc": "You can control all stages of online purchase, and independently take part in auctions for any car, no hidden fees.",
        "Customer support": "Customer support",
        "Customer support_desc": "Our team will provide full consultations for customers by telephone for purchases and car delivery.",
        "Transportation": "Transportation",
        "Transportation_desc": "We have the lowest prices for shipping.",
        "Register with Us": "Register with us",
        "Find your vehicle at auction": "Find your vehicle at auction",
        "Payment for your vehicle": "Payment for your vehicle",
        "Ocean Shipping": "Ocean Shipping",
        "Sign a contract and place a deposit": "Sign a contract and place a deposit",
        "Bidding at auction": "Bidding at auction",
        "Ground Shipping to US port": "Ground Shipping to US port",
        "Customs clearance": "Ground Shipping to Azerbaijan",
        "Useful Links": "Useful Links",
        "Contact Info": "Contact Info",
        "footer-about": "Our service as an Auto Trader company is to provide fully insured transportation of cars from the United States, Korea, Japan and European countries to Azerbaijan. It is also a chance to directly participate in insurance auctions in the United States (Copart, IAAI, Manheim, etc.).",
        "doc-desc": "This cost includes processing and mailing documents. After customs clearance in the US, your documents will be sent to our representative in your country, so you will receive them with your vehicle",
        "insurance-desc": "Ocean shipping insurance is optional, but strongly recommended for all international shipments",
        "shipping-desc": "We provide vehicle shipping services from the USA to your country. Your vehicle will be loaded into container and delivered to the port.",
        "final-bid-desc": "Final Bid at Auction you are going to bid at auction.",
        "auction-desc": "After you win, the auction will charge you a fee based on the bid amount. You can check this amount in our fee calculator before bidding.",
        "poti-baku-desc": "Shipping costs from Georgia to Baku",
        "service-desc": "Service fee for participating in an auction on behalf of a customer",
        "Home": "Home",
        "About": "About",
        "Cars": "Cars",
        "Blog": "Blog",
        "Gallery": "Gallery",
        "Shop": "Shop",
        "Contact": "Contact",
        "VIN": "VIN",
        "Title Code": "Title Code",
        "Odometer": "Odometer",
        "Auction Highlights": "Auction Highlights",
        "Primary Damage": "Primary Damage",
        "Secondary Damage": "Secondary Damage",
        "Vehicle Type": "Vehicle Type",
        "Color": "Color",
        "Engine": "Engine",
        "Cylinders": "Cylinders",
        "Transmission": "Transmission",
        "Drive": "Drive",
        "Fuel": "Fuel",
        "Keys": "Keys",
        "Special Note": "Special Note",
        "Location": "Location",
        "Sale Date": "Sale Date",
        "Sale Status": "Sale Status",
        "Sale Name": "Sale Name",
        "Lane/Item/Grid/Row": "Lane/Item/Grid/Row",
        "Last Updated": "Last Updated",
        "year": "Year",
        "make": "Make",
        "modelGroup": "Model Group",
        "model": "Model",
        "Model": "Model",
        "bodyStyle": "Body Style",
        "color": "Color",
        "primary_damage": "Primary Damage",
        "engineSize": "Engine Size",
        "locationName": "Location",
        "vehicleType": "Vehicle Type",
        "saleDate": "Sale Date",
        "odometer": "Odometer",
        "Image": "Image",
        "Lot": "Lot",
        "Year": "Year",
        "Make": "Make",
        "Sale Location": "Sale Location",
        "Bid": "Bid",
        "Order": "Order",
        "See Deatils": "See Deatils",
        "2DR SPORT UTILITY": "2DR SPORT UTILITY",
        "3DR EXT CAB PICKUP": "3DR EXT CAB PICKUP",
        "4DR EXT": "4DR EXT",
        "4DR SPORT UTILITY": "4DR SPORT UTILITY",
        "BUS": "BUS",
        "CARGO VAN": "CARGO VAN",
        "CHASSIS": "CHASSIS",
        "CLUB CAB": "CLUB CAB",
        "CONVENTIONAL CAB": "CONVENTIONAL CAB",
        "CONVERTIBLE": "CONVERTIBLE",
        "COUPE": "COUPE",
        "COUPE 3DR": "COUPE 3DR",
        "CREW CHASSIS": "CREW CHASSIS",
        "CREW PICKUP": "CREW PICKUP",
        "CUTAWAY": "CUTAWAY",
        "ENDURO": "ENDURO",
        "EXTENDED": "EXTENDED",
        "HATCHBAC": "HATCHBAC",
        "LIMOUSINE": "LIMOUSINE",
        "MOTOR SCOOTER": "MOTOR SCOOTER",
        "MOTORIZED HOME": "MOTORIZED HOME",
        "PICKUP": "PICKUP",
        "RACER": "RACER",
        "ROAD/STREET": "ROAD/STREET",
        "ROADSTER": "ROADSTER",
        "SEDAN 4DR": "SEDAN 4DR",
        "SPORT PICKUP": "SPORT PICKUP",
        "SPORTS VAN": "SPORTS VAN",
        "STATION WAGON": "STATION WAGON",
        "TILT CAB": "TILT CAB",
        "UTILITY": "UTILITY",
        "BEIGE": "BEIGE",
        "BLACK": "BLACK",
        "BLUE": "BLUE",
        "BROWN": "BROWN",
        "BURGUNDY": "BURGUNDY",
        "BURN": "BURN",
        "CHARCOAL": "CHARCOAL",
        "CREAM": "CREAM",
        "GOLD": "GOLD",
        "GRAY": "GRAY",
        "GREEN": "GREEN",
        "MAROON": "MAROON",
        "ORANGE": "ORANGE",
        "PINK": "PINK",
        "PURPLE": "PURPLE",
        "RED": "RED",
        "SILVER": "SILVER",
        "TAN": "TAN",
        "TEAL": "TEAL",
        "TURQUOISE": "TURQUOISE",
        "TWO TONE": "TWO TONE",
        "UNKNOWN -": "UNKNOWN",
        "WHITE": "WHITE",
        "YELLOW": "YELLOW",
        "ALL OVER": "ALL OVER",
        "BIOHAZARD/CHEMICAL": "BIOHAZARD/CHEMICAL",
        "BURN - ENGINE": "BURN - ENGINE",
        "BURN - INTERIOR": "BURN - INTERIOR",
        "DAMAGE HISTORY": "DAMAGE HISTORY",
        "FRAME DAMAGE": "FRAME DAMAGE",
        "FRONT END": "FRONT END",
        "HAIL": "HAIL",
        "MECHANICAL": "MECHANICAL",
        "MINOR DENT/SCRATCHES": "MINOR DENT/SCRATCHES",
        "MISSING/ALTERED VIN": "MISSING/ALTERED VIN",
        "NORMAL WEAR": "NORMAL WEAR",
        "PARTIAL REPAIR": "PARTIAL REPAIR",
        "REAR END": "REAR END",
        "REJECTED REPAIR": "REJECTED REPAIR",
        "ROLLOVER": "ROLLOVER",
        "SIDE": "SIDE",
        "STRIPPED": "STRIPPED",
        "TOP/ROOF": "TOP/ROOF",
        "UNDERCARRIAGE": "UNDERCARRIAGE",
        "VANDALISM": "VANDALISM",
        "WATER/FLOOD": "WATER/FLOOD",
        "Car": "Car",
        "Search": "Search",
        "Clear Search": "Clear Search",
        "Filters": "Filters",
        "Bid Information": "Bid Information",
        "Name": "Name",
        "Phone Number": "Phone Number",
        "Email": "Email",
        "Order Details": "Order Details",
        "Order Now": "Order Now",
        "Sale Information": "Sale Information",
        "Calculate the final price": "Calculate the final price",
        "Enter your Bid": "Enter your Bid",
        "Auction Location": "Auction Location",
        "Shipping to Country": "Shipping to Country",
        "Final Bid at Auction": "Final Bid at Auction",
        "Documentation Fee": "Documentation Fee",
        "Shipping Fee": "Shipping Fee",
        "Service Fee": "Service Fee",
        "Cargo Insurance": "Cargo Insurance",
        "Final Price": "Final Price",
        "Bid Status": "Bid Status",
        "Buy it Now Price": "Buy it Now Price",
        "Current Bid": "Current Bid",
        "Seller Reserve": "Seller Reserve",
        "Time Left": "Time Left",
        "Find Your Next Auction Car from USA": "Find Your Next Auction Car from USA",
        "Choose from used Cars, Trucks and SUV": "Choose from used Cars, Trucks and SUV",
        "Browse Popular Vehicles in Azerbaijan": "Browse Popular Vehicles",
        "View Full Auto Auction Inventory": "View Full Auto Auction Inventory",
        "Popular Makes": "Popular Makes",
        "Vehicle Types": "Vehicle Types",
        "Damage Types": "Damage Types",
        "Sale Start At": "Sale Start At",
        "Front Wheel Drive:": "Front Wheel Drive:",
        "Rear Wheel Drive": "Rear Wheel Drive",
        "All Wheel Drive": "All Wheel Drive",
        "SPORT UTILITY": "SPORT UTILITY",
        "VAN CAMPER": "VAN CAMPER",
        "TRACTOR": "TRACTOR",
        "TANDEM": "TANDEM",
        "STEP VAN": "STEP VAN",
        "SEDAN 2DR": "SEDAN 2DR",
        "MOTO CROSS": "MOTO CROSS",
        "INCOMPLE": "INCOMPLE",
        "INCOMP PASSENGER": "INCOMP PASSENGER",
        "GLIDERS": "GLIDERS",
        "DIRT": "DIRT",
        "CONVERTIBLE ": "CONVERTIBLE ",
        "ALL TERRAIN": "ALL TERRAIN",
        "4DR WAGO": "4DR WAGO",
        "SALE DATE": "SALE DATE",
        "VEHICLE TYPE": "VEHICLE TYPE",
        "ATVS": "ATVS",
        "BOATS": "BOATS",
        "CARS": "CARS",
        "DIRT BIKES": "DIRT BIKES",
        "HEAVY DUTY TRUCKS": "HEAVY DUTY TRUCKS",
        "HOMEOWNER'S": "HOMEOWNER'S",
        "INDUSTRIAL EQUIPMENT": "INDUSTRIAL EQUIPMENT",
        "JET SKIS": "JET SKIS",
        "MEDIUM DUTY TRUCKS": "MEDIUM DUTY TRUCKS",
        "MOTORCYCLE": "MOTORCYCLE",
        "RECREATIONAL VEHICLES": "RECREATIONAL VEHICLES",
        "SNOWMOBILE": "SNOWMOBILE",
        "TRALIERS": "TRALIERS",
        "LESS": "LESS",
        "ALL ": "ALL ",
        "MANUAL": "MANUAL",
        "AUTOMATIC": "AUTOMATIC",
        "TRANSMISSION": "TRANSMISSION",
        "COLOR": "COLOR",
        "GREY": "GREY",
        "REPLACED VIN": "REPLACED VIN",
        "Othr": "Other",
        "About&FAQ": "About&FAQ",
        "Services": "Services",
        "Team": "Team",
        "Azerbaijan": "Azerbaijan",
        "Georgia": "Georgia",
        "D": "D",
        "h": "h",
        "m": "m",
        "d": "d",
        "h": "h",
        "min": "min",
        "sec": "sec",
        "Similar Vehicles": "Similar Vehicles",
        "car_auction_price_msg": "Final Bid at Auction",
        "customs_nav": "Customs Calculator",
        "calculator_nav": "Payment Calculator",
        "step": "Step",
        "check_vin": "VIN Check",
        "calculate": "Hesabla",
        "warning": "Fill this field",
        "passenger_car": "Passenger Car",
        "bus": "Bus",
        "petrol": "Petrol",
        "diesel": "Diesel",
        "gas": "Gas",
        "hybrid_gasoline": "Hybrid-gasoline",
        "hybrid_diesel": "Hybrid-diesel",
        "electric": "Electric",
        "country_of_origin_option1": "Other Countires",
        "country_of_origin_option2": "Produced in the country with which a free trade agreement has been concluded, and imported from there",
        "import_customs_duty": "Import customs duty",
        "value_added_tax": "Value added tax (VAT)",
        "customs_fees_for_customs_clearance_of_goods": "Customs fees for customs clearance of goods",
        "excise_tax": "Excise tax",
        "customs_fees_for_issuing_certificates": "Customs fees for issuing certificates",
        "electronic_customs_service_fee": "Electronic customs service fee",
        "VAT_on_electronic_customs_services": "VAT on electronic customs services",
        "facebook": "Facebook",
        "instagram": "Follow us",
        "filter_more": "For detailed search ",
        "lang.send_message": "Offer your bid",
        "send": "Send",

        "home_site": {
            "confirm_to_continue": "Are you sure you want to continue?",
            "home_slide_2": "Insured and safe delivery of your car from USA",
            "home_slide_3": "Offering to customers the cars which have clear history report",
            "we_are_the_best": "We are the best",
            "home_slide_1": "Order car from the USA with the payment of 35% of its value",
            "cars_in_auction": "Cars in Auction",
            "brand": "Brand",
            "model": "Model",
            "customer": "Customer",
            "order": "Order",
            "testimonial": "Testimonial",
            "shop": "Shop",
            "ban_type": "Ban type",
            "year": "Year",
            "status": "Status",
            "mileage": "Mileage",
            "color": "Color",
            "speedbox": "Speed box",
            "location": "Location",
            "fuel_type": "Fuel type",
            "get_a_question": "Get a question",
            "useful_links": "Useful Links",
            "contact_info": "Contact Info",
            "auto_trader": "Auto Trader",
            "all_rights_reserved": "All Rights Reserved",
            "get_in_touch": "Get In Touch",
            "car_list": "Car List",
            "filtering": "Filtering",
            "description": "Description",
            "video": "Video",
            "location": "Location",
            "similar_cars": "Similar Cars",
            "overview": "Overview",
            "car_details": "Car Details",
            "home": "Home",
            "about_us": "About us",
            "frequently_asked_questions": "Frequently Asked Questions",
            "services": "Services",
            "our services": "Our Services",
            "read_more": "Read More",
            "participate_in_auctions": "Participate in Auctions",
            "service_schedule": "Service Schedule",
            "your_name_and_surname": "Your name and surname",
            "contact_info_phone_or_email": "Contact Info (phone or email)",
            "subject": "Subject",
            "your_message": "Your Message",
            "calculator": "Calculator",
            "auction": "Auction",
            "send": "Send",
            "phone": "Phone",
            "email": "Email",
            "dont_empty_this_field": "Dont't empty this field!",
            "social_media": "Social Media",
            "contact": "Contact",
            "contact_us": "Contact Us",
            "team": "Team",
            "blog_details": "Blog Details",
            "recent_blogs": "Recent Blogs",
            "about_n_faq": "About&FAQ",
            "cars": "Cars",
            "shop": "Shop",
            "shop_list": "Shop List",
            "gallery": "Gallery",
            "videos": "Videos",
            "images": "Images",
            "blog": "Blog",
            "team_details": "Team Details",
            "team_member": "Team Member",
            "biography": "Biography",
            "recent_cars": "Recent Cars",
            "city": "City",
            "states": "States",
            "port": "Port",
            "cars_auction_price": "Car's Auction Price",
            "auction_company": "Auction Company",
            "calculate": "Calculate",
            "search": "Search",
            "are_you_a_robot": "Are you a robot?",
        },
        'NORMAL WEAR': 'NORMAL WEAR', 'LOW DAMAGE': 'LOW DAMAGE', 'HALL': 'HALL',
        'MINOR DENT/SCRATCHES': 'MINOR DENT/SCRATCHES', 'MEDIUM - HEAVY DAMAGE': 'MEDIUM - HEAVY DAMAGE',
        'ALL OVER': 'ALL OVER', 'BIOHAZARD/CHEMICAL': 'BIOHAZARD/CHEMICAL', 'BURN': 'BURN',
        'BURN - ENGINE': 'BURN - ENGINE', 'BURN - INTERIOR': 'BURN - INTERIOR', 'DAMAGE HISTORY': 'DAMAGE HISTORY',
        'FRAME DAMAGE': 'FRAME DAMAGE', 'FRONT END': 'FRONT END', 'MECHANICAL': 'MECHANICAL',
        'MISSING/ALTERED VIN': 'MISSING/ALTERED VIN', 'PARTIAL REPAIR': 'PARTIAL REPAIR', 'REAR END': 'REAR END',
        'REJECTED REPAIR': 'REJECTED REPAIR', 'REPLACED VIN': 'REPLACED VIN', 'ROLLOVER': 'ROLLOVER', 'SIDE': 'SIDE',
        'STRIPPED': 'STRIPPED', 'TOP/ROOF': 'TOP/ROOF', 'UNDERCARRIAGE': 'UNDERCARRIAGE', 'UNKNOWN': 'UNKNOWN',
        'VANDALISM': 'VANDALISM', 'WATER/FLOOD': 'WATER/FLOOD',
        "price": "Price"

    },
    "RUS": {},
    "AZE": {
        "about_the_country_of_origin": "Mənşə (istehsal) ölkəsi və göndərən ölkə haqqında",
        "engine_capacity_home_calculator": "Mühərrikin həcmi (cm3)",
        "customs_value_of_car": "Avtomobilin gömrük dəyəri",
        "Automobile": "Avtomobil",
        "date_of_issue": "Buraxılış tarixi",
        "total_customs_payment": "Cəmi gömrük ödənişi",
        "AUTOMOBILE": "Avtomobil",
        "LightBlue": "Açıq mavi",
        "FrontWheelDrive": "Ön",
        "Gasoline": "Benzin",
        "AUTOMATIC": "Avtomat",
        "AutomaticTransmission": "Avtomat",
        "ECVT AUTOMATIC": "E-CVT Avtomat",
        "MANUAL": "Mexaniki",
        "ManualTransmission": "Mexaniki",
        "Unknown": "Bilinmir",
        "FLEXIBLE FUEL": "İkili yanacaq",
        "shipping_fee": "Gəmi daşınması",
        "FlexibleFuel": "İkili yanacaq",
        "GAS": "Qaz",
        "Gasoline": "Benzin",
        "Other": "Digər",
        "cost_of_delivery_to_baku": "Poti-Bakı daşınma",
        "Actual": "(yoxlanılıb)",
        "NO": "Xeyr",
        "YES": "Bəli",
        "4x4 w/Front Whl Drv": "4x4 w/Front Whl Drv",
        "4x4 w/Rear Wheel Drv": "4x4 w/Rear Wheel Drv",
        "4X4Drive": "4X4Drive",
        "All wheel drive": "Tam ",
        "AllWheelDrive": "Tam ",
        "Front-wheel Drive": "Ön",
        "FrontWheelDrive": "Ön",
        "RearWheelDrive": "Arxa",
        "BLACK": "QARA",
        "BLUE": "MAVİ",
        "type_of_vehicle": "Nəqliyyat vasitəsinin növü",
        "engine_type": "Mühərrik növü",
        "Burgundy": "Burgundy",
        "detailed_customs_fee_calculator_msg": "Avtomobilin gömrük rüsumu və digər ödənişlərinin hesablanması",
        "detailed_customs_fee_calculator": "Gömrük kalkulyatoru",
        "Gold": "Qızılı",
        "customs_fee": "Gömrük rüsumu",
        "Gray": "Boz",
        "GREEN": "YAŞIL",
        "LightBlue": "Açıq mavi",
        "Maroon": "Tünd qırmızı",
        "Red": "Qırmızı",
        "Silver": "Gümüş",
        "TAN": "TAN",
        "White": "Ağ",
        "Actual": "(yoxlanılıb)",
        "EXEMPT": "EXEMPT",
        "InoperableDigitalDash": "Odometr işləmir",
        "NOT ACTUAL": "(yoxlanılmayıb)",
        "NotActual": "(yoxlanılmayıb)",
        "NotRequired/Exempt": "İstismarı bitib",
        "ALL OVER": "Hər tərəf",
        "AllOver": "Hər tərəf",
        "Biohazard": "Qan ləkəsi",
        "Electrical": "Elektrik",
        "EngineDamage": "Mühərrik problemi",
        "Frame": "Çərçivə",
        "FRONT END": "Ön",
        "Front&Rear": "Ön və Arxa",
        "FrontEnd": "Ön",
        "LeftFront": "Sol ön",
        "LeftRear": "Sol arxa",
        "LeftSide": "Sol",
        "Mechanical": "Mexaniki",
        "MINOR DENT/SCRATCHES": "Kiçik əzik / Cızıqlar",
        "NORMAL WEAR": "Normal köhnəlmə",
        "Rear": "Arxa",
        "REAR END": "Arxa",
        "Repossession": "Geri alınmış",
        "RightFront": "Sağ ön",
        "RightSide": "Sağ",
        "Rollover": "Aşmış",
        "SIDE": "Yan",
        "Unknown": "Bilinmir",
        "VANDALISM": "Vandalizm",
        "4DOOREXTENDEDCABPICKUP": "Pickap 4 qapı (genişləndirilmiş)",
        "CONVERTIBLE": "Kabriolet",
        "COUPE": "Kupe",
        "CREWPICKUP": "Pikap",
        "HATCHBACK2DR.": "Hetçbek 2 qapı",
        "HATCHBACK4DOOR": "Hetçbek 4 qapı",
        "HATCHBACK4DR.": "Hetçbek 4 qapı",
        "ROADSTER": "Rodster",
        "SEDAN": "Sedan",
        "SEDAN4DOOR": "Sedan 4 qapı",
        "SEDAN4DR.": "Sedan 4 qapı",
        "SUPERCABPICKUP": "Pikap",
        "UTILITY": "Utility",
        "WAGON4DR.": "Vagon",
        "search_bar_msg": "Marka, model və lot nömrəsi üzrə axtarış",
        "similar_vehicles": "Oxşar nəqliyyat vasitələri",
        "register_now": "Register Now",
        "register_today_and_get_free": "Register today and get Free Membership! It’s fast and easy.",
        "bid": "Hərrac dəyəri",
        "sale_location": "Satış yeri",
        "sale_information": "Hərrac məlumatları",
        "details": " məlumatları",
        "watch": "Bax",
        "shipping": "Daşınma",
        "vin": "VIN",
        "no_longer_available_for_bidding": "Təklif müddəti bitmişdir",
        "final_price_estimator": "Final Price Estimator",
        "title_code": "Sənədi",
        "odometer": "Odometer",
        "primary_damage": "Əsas zədə",
        "secondary_damage": "Digər zədə",
        "body_style": "Ban növü",
        "vehicle_type": "Nəqliyyat vasitəsinin növü",
        "color": "Rəng",
        "engine": "Mühərrik",
        "damage_type": "Zədə növü",
        "cylinders": "Silindrlər",
        "transmission": "Sürətlər qutusu",
        "drive": "Ötürücü",
        "fuel": "Yanacaq",
        "keys": "Açarlar",
        "special_note": "Xüsusi qeyd",
        "lot": "Lot",
        "bid_information": "Hərrac məlumatları",
        "bid_status": "Təklif statusu",
        "current_bid": "Hazırkı təklif",
        "time_left": "Qalan vaxt",
        "rentals": "İcarə",
        "final_bid": "Həracda son təklif",
        "auction_fee": "Hərrac vergisi",
        "insurance_fee": "Sığorta",
        "service_fee": "Xidmət haqqı",
        "transfer_fee": "Daşınma xərci",
        "documentation_fee": "Sənədləşmə xərci",
        "enter_bid": "Qiymət təklifiniz",
        "auction": "Hərrac",
        "from_country": "Göndərilən ölkə",
        "from_port": "Göndərilən liman",
        "to_country": "Çatdırılan ölkə",
        "azerbaijan": "Azərbaycan",
        "georgia": "Gürcüstan",
        "to_port": "Çatdırılan liman",
        "location": "Yer",
        "sale_date": "Hərrac tarixi",
        "sale_status": "Satış növü",
        "lane": "Sıra",
        "item": "Item",
        "grid": "Cədvəl",
        "row": "Hərrac sırası",
        "hybrid": "Hibrid",
        "exotic": "Ekzotik",
        "last_updated": "Sonuncu yenilənmə",
        "show_more": "Ardını göstər",
        "show_less": "Daha az göstər",
        "view_vehicle": "Avtomobilə Bax",
        "final_price": "Yekun qiymət",
        "view_full_auto_auction_inventory": "Amerikada hərracda olan avtomobillər",
        "popular_makes": "Məşhur markalar",
        "browse_popular": "Azərbaycanda ən çox sifariş verilən avtomobillər",
        "choose_from_over": "ABŞ-ın sığorta hərraclarında olan minlərlə avtomobil arasından seçim edin",
        "find_your_next_auction": "Amerika Hərracından avtomobil axtarışı",
        "how_to_buy_and_ship_your_vehicle": "Amerikadan avtomobili necə almaq olar?",
        "day": "Gün",
        "sign_a_contract": "Müqavilə imzalanması",
        "find_your_vehicle_at_auction": "Avtomobil seçimi və məsləhət xidməti",
        "bidding_at_auction": "Hərracda iştirak",
        "shipping_to": " Çatdırılma",
        "payment_for_auction": "Ödənişin köçürülməsi",
        "ground_shipping": "Azərbaycana çatdırılma",
        "ocean_shipping_to": "Gürcüstan portlarına çatdırılma",
        "customs_clearance": "Gömrük rəsmiləşdirilməsi",
        "official_representative": "Hərracda iştirak",
        "official_representative_msg": "Müştərilər yerli alıcılar üçün əlçatmaz olan Amerika, Avropa və Koreya bazarlarından aşağı qiymətə avtomobil seçmək imkanına sahibdirlər. Şirkət dünyanın aparıcı avtomobil auksionlarında (Copart, IAAI, Manheim və s.) iştirak etmək hüququna malikdir. Şirkət xarici bazarlarda heç bir vasitəçi olmadan birbaşa iştirak edir, nəticədə alınan avtomobilin qiyməti yerli bazar qiymətinə nisbətən daha aşağı olur.",
        "low_transaction_fee": "Low Transaction Fee",
        "low_transaction_fee_msg": "The lowest auction and transaction fees on the market. Price includes consultations with company auction experts.",
        "online_platform": "Onlayn platforma",
        "online_platform_msg": "You can control all stages of online purchase, and independently take part in auctions for any car, no hidden fees.",
        "customer_support": "Customer Support",
        "customer_support_msg": "Our team will provide full consultations for customers by telephone for purchases and car delivery.",
        "transportation_to_pak": "Transportation to Azerbaijan",
        "transportation_to_pak_msg": "We have the lowest prices for shipping to Azerbaijan.",
        "payment_calculator": "Hərrac kalkulatoru",
        "payment_calculator_msg": "Avtomobilin hərrac vergisi və daşınması daxil olmaqla tam dəyərini hesabla",
        "get_price_breakdown": "Get a full-price breakdown for your vehicle",
        "get_price_breakdown_msg": "We'll get back to you with final prices, including customs fees and shipping",
        "request_information": "Request Information",
        "check_vin_history": "Check Vin History",
        "check_vin_history_msg1": "ClearVin is a trusted source of vehicle history information and is an approved NMVTIS data provider.",
        "check_vin_history_msg2": "ClearVin reports provide you with thorough vehicle information which including title and brand history, insurance claim information, recall events, loan and retail value and much more.",
        "check_vin_history_msg3": "Buy safely - view detailed information about the car instantly with ClearVin vehicle history reports.",
        "lookup_vin_now": "Lookup VIN Now",
        "enter_17_char_vin_number": "Enter 17 Character VIN Number",
        "where_to_find_vin": "Where to find VIN?",
        "no_vin_click_here": "No VIN? Click here",
        "got_shipping_questions": "Got shipping questions?",
        "got_shipping_questions_msg": "Leave a request to contact a manager",
        "request_callback": "Request a Callback",
        "your_name": "Adınız",
        "international_shipping": "International Shipping – Import cars to Azerbaijan",
        "international_shipping_msg": "We offer competitive shipping services to anywhere in the world. We are a licensed NVOCC and can provide you the best price in the market. Import your next car to Azerbaijan",
        "about_autobidmaster": "About Auto Trader",
        "about_autobidmaster_msg": "With more than 10 years of experience in the automotive industry, we’re here to help you understand the auction process, as well as the best delivery options. We have offices in both the USA and Azerbaijan that work together to get your vehicle to you. Auto Trader is the only Copart Authorized Online Auction Platform in Azerbaijan.",
        "order_shipping": "Çatdırılma sifarişi",
        "delivery_from": "DELIVERY FROM AUCTION TO THE PORT",
        "delivery_from_msg": "Our experts will manage the delivery of your vehicle from the auction location to the port in the US. The transit time depends on the location of the auction yard and destination port.",
        "loading_and_sailing": "LOADING AND SAILING",
        "loading_and_sailing_msg": "We provide shipping services from the USA and Canada. For shipments from the US we use 7 ports: New Jersey, Savannah, Miami, Houston, Los Angeles, Seattle, Chicago.",
        "ocean_sailing_and_unloading": "OCEAN SHIPPING AND UNLOADING",
        "ocean_sailing_and_unloading_msg": "Auto Trader has offices in other countries that are happy to assist you with unloading and customs clearance. We provide you with the final price of your vehicle including shipping cost.",
        "opennig_time": "İş vaxtları:",
        "your_name": "Adınız",
        "enter_lot_or_vin": "Enter Lot # or VIN",
        "print": "Çap edin",
        "copy": "Surətini çıxardın",
        "shipping_quote": "Shipping Quote",
        "complete_order": "Complete Order",
        "order_placed": "Order Placed",
        "search": "Axtar",
        "all_makes": "Marka",
        "all_models": "Model",
        "all_locations": "Şəhər",
        "from_year": "İl (min.)",
        "to_year": "İl (maks.)",
        "first_name": "Ad",
        "last_name": "Soyad",
        "email": "Email",
        "by_clicking_you_agree": "By clicking 'REGISTER NOW' you agree to Auto Trader",
        "terms_and_conditions": "Terms and Conditions",
        "already_a_member": "Already a member?",
        "or_continue_with": "OR CONTINUE WITH",
        "continue_with_facebook": "Continue With Facebook",
        "continue_with_google": "Continue With Google",
        "quick_view": "Bax",
        "sign_in": "Sign In",
        "order_now": "İndi sifariş edin",
        "phone": "Telefon",
        "vehicles_sold_msg": "Vehicles sold 'as is - where is', all sales are final.",
        "want_it_now": "Want It Now?",
        "buy_it_now_price": "Buy It Now Price",
        "more_vin_details": "More Vin Details",
        "vehicle_history": "Vehicle History",
        "get_full_history_report": "Get Full History Report",
        "previous_auction_sales": "Previous Auction Sales",
        "record": "Record",
        "found": "Found",
        "previous_owners": "Previous Owners",
        "title_brand_history": "Title Brand History",
        "lien_impound_theft": "Lien/Impound/Theft",
        "safety_recalls": "Safety Recalls",
        "additional_photos": "Additional Photos",
        "photos": "Photos",
        "clear_vin": "ClearVin",
        "make_offer": "Make Offer",
        "buy_it_now": "İndi al",
        "calculate_final_price_for_any_vehicle": "Yekun qiyməti görmək üçün təklifinizi daxil edin",
        "apply_filter": "Filterlə",
        "filters": " Filtrlər",
        "clear_filter": "Filtrləri sil",
        "newly_added_lots": "Yeni əlavə edilmiş",
        "make": "Make",
        "year": "İl",
        "search_h1": "AMERİKADAN AVTOMOBİL SİFARİŞİ",
        "search_h1_msg": "Amerikanın sığorta hərraclarında işlənmiş avtomobilin alınması prosesi bir neçə mərhələdən keçir. İlk öncə almaq istədiyiniz avtomobilin markasını, modelini, ilini və komplektasiyasını bizə bildirin. Bizim tərəfimizdən bu tələblərə uyğun olan, yaxın vaxtda auksiyonlarda oynanılacaq maşınlar seçilib Sizə  təklif olunacaq. Təklif olunan avtomobillər tərəfimizdən araşdırılır, yalnız güclü zədəsi, suda batmış və digər ciddi problemləri olmayan avtomobillər seçilir. Avtomobil seçildikdən sonra auksiyondan öncə hərrac dəyərinin 10% məbləğində hüquqi cəhətdən rəsmiləşdirilmiş qaydada depozit yerləşdirilir. Depozit yalnız o halda geri qaytarılmır ki, müştəri avtomobili auksiyonda udduqdan sonra alış dəyərini ödəməkdən imtina etsin. Belə olduqda auksiyon saytları tərəfindən cərimə olunur və bu məbləğ birbaşa olaraq oraya ödənilir.",
        "search_h2": "HƏRRACDA İŞTİRAK",
        "search_h2_msg": "Avtomobil seçildikdən sonra auksiyonda oynamaq üçün maksimum qiymət təyin edilir. Yekun qiymət hərracda udacağımız məbləğdən asılıdır.  Bunun üçün ilk növbədə siz büdcənizi ( Bakıya qədər olan) qeyd edirsiniz. Bu büdcəyə uyğun olaraq biz hərracda hər bir maşının maksimum neçəyə qədər oynayacağımızı müyyən edirik ki, son nəticədə hərrac vergisi daşınma da qiymətə əlavə olunduqda sizin büdcəni keçməsin.Siz hərrac prosesini video zənglə və ya şəxsən ofisimizə gələrək izləyə bilərsiniz. Avtomobilin alış dəyəri və auksion vergisi avtomobil udulduqdan sonrakı növbəti gün ərzində bank vasitəsi ilə satıcı şirkətə ödənilir.",
        "search_h3": "ÇATDIRILMA",
        "search_h3_msg": "Avtomobilin alış  dəyəri ödənildikdən sonra ən geci 10 gün ərzində satış meydançasından yola salınır və avtomobil 45-90 gün ərzində Gürcüstan limanlarından birinə (əsasən Poti) çatdırılır. Avtomobilin harada olduğu haqqında məlumatı olması üçün müştəriyə izləmə kodu və ya konteyner nömrəsi  verilir və müştəri istədiyi zaman bu məlumatı görə bilir. Avtomobil porta çatdıqdan sonra daşınma xərcləri ödənilir. Daşınma xərcləri ştatdan asılı olaraq. Hər bir şəhər üzrə daşınma qimətini saytımızdakı “Hərrac kalkulatoru” bölməsindən öyrənə bilərsiniz",
        "salvage_cars_for_sale": "Hərracda olan avtomobillər",
        "results_found": "Nəticə tapıldı",
        "save_search": "Save Search",
        "save_search_msg": "Press “Save Search” button to save your search here and you will get notified with updates.",
        "saved_search": "Saved Search",
        "image": "Şəkil",
        "electric": "Electric",
        "see_details": "Ətraflı",
        "model": "Model",
        "damaged_salvage": "Damaged Salvage",
        "list": "Siyahı",
        "address_line": " Heydər Əliyev prospekti 115, Sport Plaza Hotel & Apartments 187B",
        "monday": "Bazar ertəsi",
        "friday": "Cümə günü",
        "call_us": "Bizə zəng edin",
        "text_us": "Bizə yazın",
        "viber": "Viber",
        "whatsapp": "Whatsapp",
        "featured_items": "Featured Items",
        "ownership_doctypes": "Ownership Doc Types",
        "search_by_states": "Search by States",
        "home": "Əsas səhifə",
        "copyright_msg": "Copyright &copy; 2022 Auto Trader, LLC All Rights Reserved. The use of this Web site constitutes acceptance of the Terms of Service and Privacy Policy. Sitemap. Articles. Auto Trader, LLC is not owned by or affiliated with Copart, Inc, or its subsidiaries. All vehicles are purchased from Auto Trader not Copart.",
        "how_to_buy": "How to Buy",
        "find_vehicles": "Find Vehicles",
        "live_auctions": "Live Auctions",
        "shipping": "Daşınma",
        "support": "Dəstək",
        "services": "Xidmətlər",
        "featured_items": "Featured Items",
        "cars_5_years_or_less": "Cars 5 years or less",
        "clean_title": "Problemsiz sənəd",
        "front_end": "Front End",
        "hail": "Hail",
        "register_to_buy": "Register to Buy",
        "lots_with_bids": "Lots With Bids",
        "new_items": "New Items",
        "no_bids_yet": "No Bids Yet",
        "normal_wear": "Normal Wear",
        "pure_sales_items": "Pure Sales Items",
        "runs_and_drives": "Xodlanır və sürülür",
        "salvage_title": "Salvage Title",
        "selling_today": "Selling Today",
        "auction_locations": "Auction Locations",
        "vandalism": "Vandalism",
        "search_auctions": "Search Auctions",
        "flood_damage": "Flood Damage",
        "water_flood": "Su/Daşqın",
        "no_damage": "No Damage",
        "auctions": "Auctions",
        "rvs": "RVs",
        "company_information": "Company Information",
        "sd": "sd",
        "vehicle_finder": "Vehicle Finder",
        "hail_damage": "Hail Damage",
        "autobidmaster_review": "Auto Trader Review",
        "live_auctions": "Live Auctions",
        "todays_auctions": "Today's Auctions",
        "auction_calendar": "Auction Calendar",
        "join_auctions": "Join Auctions",
        "locations": "Locations",
        "clean_title": "Clean Title ",
        "non_repairable": "Non-repairable ",
        "salvage_title": "Salvage Title ",
        "rejected_repair": "Rejected Repair ",
        "replaced_vin": "Replaced VIN ",
        "rollover": "Rollover ",
        "side": "Side ",
        "stripped": "Stripped ",
        "top_roof": "Top/Roof ",
        "undercarriage": "Undercarriage ",
        "unknown": "Bilinmir",
        "vandalism": "Vandalism ",
        "water_flood": "Su/Daşqın ",
        "all_overs": "All Overs ",
        "biohazard_chemical": "Biohazard/Chemical ",
        "burn": "Burn ",
        "burn___engine": "Burn - Engine ",
        "burn___interio": "Burn - Interior",
        "damage_history": "Damage History ",
        "frame": "Frame ",
        "front_end": "Front End ",
        "hales": "Hales ",
        "mechanical": "Mechanical ",
        "minor_dent_scratches": "Minor Dent/Scratches ",
        "missing_alterd_vin": "Missing/Alterd Vin ",
        "normal_wear": "Normal Wear ",
        "partial_repair_cars": "Partial Repair Cars ",
        "rear_end": "Rear End ",
        "atvs": "ATVs ",
        "boats": "Qayıqlar",
        "cars": "Maşınlar",
        "classics": "Classics ",
        "dirt_bike": "Dirt Bikes",
        "heavy_duty_trucks": "Heavy Duty Trucks ",
        "industrial_equipment": "Industrial Equipment ",
        "jet_skis": "Jet Skis ",
        "medium_duty_trucks": "Medium Duty Trucks ",
        "motorcycles": "Motorcycles ",
        "pickup_trucks": "Pickup Trucks ",
        "recreational_vehicles": "Recreational Vehicles ",
        "suvs": "SUVs ",
        "sbowmobiles": "Sbowmobiles ",
        "trailers": "Trailers ",
        "convertible": "Convertible ",
        "coupe": "Coupe ",
        "hatchback": "Hatchback ",
        "pickup_trucks": "Pickup Trucks ",
        "seda": "Sedan",
        "suv_crossover": "Suv/Crossover ",
        "vans_minivan": "Vans/Minivan ",
        "wagon": "Wagon ",
        "minor_dent_scratches": "Minor Dent/Scratches",
        "bid_price_2000_or_less": "Bid price $2,000 or less",
        "video_guides": "Video Guides",
        "help_center": "Help Center",
        "rules_and_polices": "Rules and Polices",
        "contact_us": "Bizimlə əlaqə",
        "vehicle_history_report": "Vehicle History Report",
        "domestic_vehicle_transportation": "Domestic Vehicle Transportation",
        "international_shipping": "International Shipping",
        "business_buyers": "Business Buyers",

        "Details": "Detallar",
        "See Details": "See Details",
        "Results Found": "Results Found",
        "Search Results": "Search Results",
        "Calculator": "Kalkulyator",
        "Other": "Digər",
        "DAY": "Gün",
        "Model Group": "Model Group",
        "search_bar": " Marka, Model və Lot üzrə axtar ",
        "All Makes": "All Makes",
        "All Models": "All Models",
        "From Year": "İl(minimum)",
        "To Year": "İl(maksimum)",
        "All locations": "All locations",
        "verify-response": "PLEASE CHECK YOUR INBOX TO VERIFY YOUR EMAIL",
        "Met": "Met",
        "Auction Fee": "Hərrac xərci",
        "Not Yet Met": "Not Yet Met",
        "YOU HAVEN'T BID": "YOU HAVEN'T BID",
        "How to Buy": "How to Buy",
        "Benefits of Choosing Autotrader": "Benefits of Choosing Autotrader",
        "Official representative": "Official representative",
        "Official representative_desc": "Autotrader is the Official Authorized Copart Online Auctions Platform.",
        "Live bidding": "Live bidding",
        "Live bidding_desc": "Place your bids yourself, avoiding intermediaries and overpayments! With our license, you can buy a car from any state without restrictions.",
        "Low Transaction Fees": "Low Transaction Fees",
        "Low Transaction Fees_desc": "The lowest auction and transaction fees on the market. Price includes consultations with company auction experts.",
        "Online platform": "Onlayn platforma",
        "Online platform_desc": "You can control all stages of online purchase, and independently take part in auctions for any car, no hidden fees.",
        "Customer support": "Customer support",
        "Customer support_desc": "Our team will provide full consultations for customers by telephone for purchases and car delivery.",
        "Transportation": "Transportation",
        "Transportation_desc": "We have the lowest prices for shipping.",
        "Register with Us": "Register with us",
        "Find your vehicle at auction": "Find your vehicle at auction",
        "Payment for your vehicle": "Payment for your vehicle",
        "Ocean Shipping": "Ocean Shipping",
        "Sign a contract and place a deposit": "Sign a contract and place a deposit",
        "Bidding at auction": "Bidding at auction",
        "Ground Shipping to US port": "Ground Shipping to US port",
        "Customs clearance": "Ground Shipping to Azerbaijan",
        "Useful Links": "Faydalı Linklər",
        "Contact Info": "Əlaqə məlumatları",
        "footer-about": "Our service as an Auto Trader company is to provide fully insured transportation of cars from the United States, Korea, Japan and European countries to Azerbaijan. It is also a chance to directly participate in insurance auctions in the United States (Copart, IAAI, Manheim, etc.).",
        "doc-desc": "This cost includes processing and mailing documents. After customs clearance in the US, your documents will be sent to our representative in your country, so you will receive them with your vehicle",
        "insurance-desc": "Ocean shipping insurance is optional, but strongly recommended for all international shipments",
        "shipping-desc": "We provide vehicle shipping services from the USA to your country. Your vehicle will be loaded into container and delivered to the port.",
        "final-bid-desc": "Final Bid at Auction you are going to bid at auction.",
        "auction-desc": "After you win, the auction will charge you a fee based on the bid amount. You can check this amount in our fee calculator before bidding.",
        "poti-baku-desc": "Shipping costs from Georgia to Baku",
        "service-desc": "Service fee for participating in an auction on behalf of a customer",
        "Home": "Əsas səhifə",
        "About": "Haqqında",
        "Cars": "Maşınlar",
        "Blog": "Bloq",
        "Gallery": "Qalereya",
        "Shop": "Mağaza",
        "Contact": "Əlaqə",
        "VIN": "VIN",
        "Title Code": "Title Code",
        "Odometer": "Odometer",
        "Auction Highlights": "Auction Highlights",
        "Primary Damage": "Birinci dərəcəli zərər",
        "Secondary Damage": "İkinci dərəcəli ziyan",
        "Vehicle Type": "Nəqliyyat vasitəsinin növü",
        "Color": "Rəng",
        "Engine": "Mühərrik",
        "Cylinders": "Cylinders",
        "Transmission": "Sürətlər qutusu",
        "Drive": "Drive",
        "Fuel": "Yanacaq",
        "Keys": "Açarlar",
        "Special Note": "Xüsusi qeyd",
        "Location": "Yer",
        "Sale Date": "Sale Date",
        "Sale Status": "Sale Status",
        "Sale Name": "Sale Name",
        "Lane/Item/Grid/Row": "Lane/Item/Grid/Row",
        "Last Updated": "Last Updated",
        "year": "İl",
        "make": "Marka",
        "modelGroup": "Model Group",
        "model": "Model",
        "Model": "Model",
        "bodyStyle": "Ban tipi",
        "color": "Rəng",
        "primary_damage": "Əsas zədə",
        "engineSize": "Mühərrik ölçüsü",
        "locationName": "Yerin adı",
        "vehicleType": "Nəqliyyat vasitəsinin növü",
        "saleDate": "Satış tarixi",
        "odometer": "Yürüş",
        "Image": "Şəkil",
        "Lot": "Lot",
        "Year": "İl",
        "Make": "Make",
        "Sale Location": "Satış yeri",
        "Bid": "Qiymət təklifi",
        "Order": "Sifariş",
        "See Deatils": "See Deatils",
        "2DR SPORT UTILITY": "2DR SPORT UTILITY",
        "3DR EXT CAB PICKUP": "3DR EXT CAB PICKUP",
        "4DR EXT": "4DR EXT",
        "4DR SPORT UTILITY": "4DR SPORT UTILITY",
        "BUS": "Avtobus",
        "CARGO VAN": "CARGO VAN",
        "CHASSIS": "CHASSIS",
        "CLUB CAB": "CLUB CAB",
        "CONVENTIONAL CAB": "CONVENTIONAL CAB",
        "CONVERTIBLE": "CONVERTIBLE",
        "COUPE": "COUPE",
        "COUPE 3DR": "COUPE 3DR",
        "CREW CHASSIS": "CREW CHASSIS",
        "CREW PICKUP": "CREW PICKUP",
        "CUTAWAY": "CUTAWAY",
        "ENDURO": "ENDURO",
        "EXTENDED": "EXTENDED",
        "HATCHBAC": "HATCHBAC",
        "LIMOUSINE": "LIMOUSINE",
        "MOTOR SCOOTER": "MOTOR SCOOTER",
        "MOTORIZED HOME": "MOTORIZED HOME",
        "PICKUP": "AZPICKUP",
        "RACER": "RACER",
        "ROAD/STREET": "ROAD/STREET",
        "ROADSTER": "ROADSTER",
        "SEDAN 4DR": "SEDAN 4DR",
        "SPORT PICKUP": "SPORT PICKUP",
        "SPORTS VAN": "SPORTS VAN",
        "STATION WAGON": "STATION WAGON",
        "TILT CAB": "TILT CAB",
        "UTILITY": "UTILITY",
        "BEIGE": "Bej",
        "BLACK": "Qara",
        "BLUE": "Mavi",
        "BROWN": "Qəhvəyi",
        "BURGUNDY": "Tünd qırmızı",
        "BURN": "BURN",
        "CHARCOAL": "Tünd göy",
        "CREAM": "Krem",
        "GOLD": "Qızılı",
        "GRAY": "Boz",
        "GREEN": "Yaşıl",
        "MAROON": "Marun",
        "ORANGE": "Narıncı",
        "PINK": "Çəhrayı",
        "PURPLE": "Bənövşəyi",
        "RED": "Qırmızı",
        "SILVER": "Gümüşü",
        "TAN": "Açıq qəhvəyi",
        "TEAL": "Açıq mavi",
        "TURQUOISE": "Firuzəyi",
        "TWO TONE": "İki rəng",
        "UNKNOWN -": "Bilinmir",
        "WHITE": "Ağ",
        "YELLOW": "Sarı",
        "ALL OVER": "Hər tərəfi",
        "BIOHAZARD/CHEMICAL": "BIOHAZARD/CHEMICAL",
        "BURN - ENGINE": "BURN - ENGINE",
        "BURN - INTERIOR": "BURN - INTERIOR",
        "DAMAGE HISTORY": "DAMAGE HISTORY",
        "FRAME DAMAGE": "FRAME DAMAGE",
        "FRONT END": "FRONT END",
        "HAIL": "HAIL",
        "MECHANICAL": "MECHANICAL",
        "MINOR DENT/SCRATCHES": "MINOR DENT/SCRATCHES",
        "MISSING/ALTERED VIN": "MISSING/ALTERED VIN",
        "NORMAL WEAR": "NORMAL WEAR",
        "PARTIAL REPAIR": "PARTIAL REPAIR",
        "REAR END": "REAR END",
        "REJECTED REPAIR": "REJECTED REPAIR",
        "ROLLOVER": "ROLLOVER",
        "SIDE": "SIDE",
        "STRIPPED": "STRIPPED",
        "TOP/ROOF": "TOP/ROOF",
        "UNDERCARRIAGE": "UNDERCARRIAGE",
        "VANDALISM": "Vandalizm",
        "WATER/FLOOD": "Su/Daşqın",
        "Car": "Maşın",
        "Search": "Axtar",
        "Clear Search": "Axtarışı silin",
        "Filters": "Filtrlər",
        "Bid Information": "Qiymət təklifinin məlumatları",
        "Name": "Ad",
        "Phone Number": "Telefon nömrəsi",
        "Email": "Email",
        "Order Details": "Sifariş detalları",
        "Order Now": "İndi sifariş edin",
        "Sale Information": "Satış məlumatı",
        "Calculate the final price": "Yekun məbləği hesablayın",
        "Enter your Bid": "Qiymət təklifinizi qeyd edin",
        "Auction Location": "Hərrac yeri",
        "Shipping to Country": "Ölkəyə çatdırılma",
        "Final Bid at Auction": "Hərracda son qiymət təklifi",
        "Documentation Fee": "Sənədləşmə xərci",
        "Shipping Fee": "Daşınma xərci",
        "Service Fee": "Xidmət haqqı",
        "Cargo Insurance": "Yüklərin sığortası (Karqo)",
        "Final Price": "Yekun məbləğ",
        "Bid Status": "Qiymət təklifi statusu",
        "Buy it Now Price": "Buy it Now Price",
        "Current Bid": "Hazırki qiymət təklifi",
        "Seller Reserve": "Seller Reserve",
        "Time Left": "Time Left",
        "Find Your Next Auction Car from USA": "Find Your Next Auction Car from USA",
        "Choose from used Cars, Trucks and SUV": "Choose from used Cars, Trucks and SUV",
        "Browse Popular Vehicles in Azerbaijan": "Browse Popular Vehicles",
        "View Full Auto Auction Inventory": "View Full Auto Auction Inventory",
        "Popular Makes": "Məşhur markalar",
        "Vehicle Types": "Nəqliyyat vasitəsinin növləri",
        "Damage Types": "Zərərin növü",
        "Sale Start At": "Sale Start At",
        "Front Wheel Drive:": "Front Wheel Drive:",
        "Rear Wheel Drive": "Rear Wheel Drive",
        "All Wheel Drive": "All Wheel Drive",
        "SPORT UTILITY": "SPORT UTILITY",
        "VAN CAMPER": "VAN CAMPER",
        "TRACTOR": "TRACTOR",
        "TANDEM": "TANDEM",
        "STEP VAN": "STEP VAN",
        "SEDAN 2DR": "SEDAN 2DR",
        "MOTO CROSS": "MOTO CROSS",
        "INCOMPLE": "INCOMPLE",
        "INCOMP PASSENGER": "INCOMP PASSENGER",
        "GLIDERS": "GLIDERS",
        "DIRT": "Kir",
        "CONVERTIBLE ": "CONVERTIBLE ",
        "ALL TERRAIN": "Bütün ərazi",
        "4DR WAGO": "4DR WAGO",
        "SALE DATE": "Satış tarixi",
        "VEHICLE TYPE": "Nəqliyyat vasitəsinin növü",
        "ATVS": "ATVS",
        "BOATS": "Qayıqlar",
        "CARS": "MAŞINLAR",
        "DIRT BIKES": "DIRT BIKES",
        "HEAVY DUTY TRUCKS": "HEAVY DUTY TRUCKS",
        "HOMEOWNER'S": "HOMEOWNER'S",
        "INDUSTRIAL EQUIPMENT": "Sənaye təhcizatı",
        "JET SKIS": "JET SKIS",
        "MEDIUM DUTY TRUCKS": "Orta rüsumlu yük maşınları",
        "MOTORCYCLE": "motosiklet",
        "RECREATIONAL VEHICLES": "RECREATIONAL VEHICLES",
        "SNOWMOBILE": "SNOWMOBILE",
        "TRALIERS": "Qoşqular",
        "LESS": "Az",
        "ALL ": "Hamısı",
        "MANUAL": "Mexaniki",
        "AUTOMATIC": "Avtomat",
        "TRANSMISSION": "TRANSMISSION",
        "COLOR": "RƏNG",
        "GREY": "Boz",
        "REPLACED VIN": "VIN dəyişmişdir",
        "Othr": "Digər",
        "About&FAQ": "Haqqında&MVS",
        "Services": "Xidmətlər",
        "Team": "Komanda",
        "Azerbaijan": "Azərbaycan",
        "Georgia": "Gürcüstan",
        "D": "D",
        "h": "h",
        "m": "m",
        "d": "d",
        "h": "h",
        "min": "min",
        "sec": "sec",
        "Similar Vehicles": "Oxşar nəqliyyat vasitələri",
        "car_auction_price_msg": "Final Bid at Auction",
        "customs_nav": "Gömrük kalkulyatoru",
        "calculator_nav": "Hərrac kalkulatoru",
        "step": "Mərhələ",
        "check_vin": "VIN yoxlanması",
        "choose": "Seçim edin",
        "calculate": "HESABLA",
        "warning": "bu hissəni boş buraxmayın",
        "passenger_car": "Minik Avtomobili",
        "bus": "Avtobus",
        "petrol": "Benzin",
        "diesel": "Dizel",
        "gas": "Qaz",
        "hybrid_gasoline": "Hibrid Benzin",
        "hybrid_diesel": "Hibrid Dizel",
        "electric": "Elektrik",
        "country_of_origin_option1": "Digər ölkələr",
        "country_of_origin_option2": "Azad ticarət sazişi bağlanan ölkədə istehsal olunub və oradan gətirilir",
        "import_customs_duty": "İdxal gömrük rüsumu",
        "value_added_tax": "ƏDV",
        "customs_fees_for_customs_clearance_of_goods": "Gömrük yığımları",
        "excise_tax": "Aksiz vergisi",
        "customs_fees_for_issuing_certificates": "Vəsiqə haqqı",
        "electronic_customs_service_fee": "Elektron gömrük xidməti haqqı",
        "VAT_on_electronic_customs_services": "Elektron gömrük xidməti üzrə ƏDV",
        "facebook": "Facebook Səhifəmiz",
        "instagram": "Bizi İnstagramda izləyim",
        "filter_more": "Daha ətraflı seçim üçün:",
        "send_message": "Qiymət təklifi göndər",
        "send": "Göndər",
        "car_about": "Ətraflı məlumat",
        "ALL OVER": "ALL OVER AZE",
        "LESS THAN 25,000": "AZE LESS THAN",
        "SPORTUTILITYVEHICLE4DOOR": "SPORTUTILITYVEHICLE-AZE",
        "AllOver": "AllOver-AZE",

        "home_site": {
            "confirm_to_continue": "Davam etmək istədiyinizə əminsiniz?",
            "home_slide_2": "Avtomobilinizin Amerikadan tam sığortalı və təhlükəsiz çatdırılması",
            "home_slide_3": "Avtomobilin tarixçəsini yoxlamaqla müştərinin istəyinə uyğun avtomobil təklifi",
            "we_are_the_best": "Biz ən yaxşısıyıq",
            "home_slide_1": "Dəyərinin 35%-ni ödəməklə Amerikadan avtomobil sifarişi",
            "cars_in_auction": "Hərracda olan avtomobillər",
            "brand": "Brend",
            "model": "Model",
            "customer": "Müştəri",
            "order": "Sifariş",
            "testimonial": "Referanslar",
            "shop": "Mağaza",
            "ban_type": "Ban tipi",
            "year": "İl",
            "status": "Status",
            "mileage": "Məsafə",
            "color": "Rəng",
            "speedbox": "Sürət qutusu",
            "location": "Yer",
            "fuel_type": "Yanacaq növü",
            "get_a_question": "Sualınız var",
            "useful_links": "Faydalı linklər",
            "contact_info": "Əlaqə məlumatları",
            "auto_trader": "Auto Trader",
            "all_rights_reserved": "Müəllif hüquqları qorunur",
            "get_in_touch": "Əlaqə saxlayın",
            "car_list": "Maşın siyahısı",
            "filtering": "Filtrlə",
            "description": "Əlavə məlumat",
            "video": "Video",
            "location": "Yer",
            "similar_cars": "Oxşar maşınlar",
            "overview": "Ümumi baxış",
            "car_details": "Maşının detalları",
            "home": "Əsas səhifə",
            "about_us": "Haqqımızda",
            "frequently_asked_questions": "Tez-tez soruşulan suallar",
            "services": "Xidmətlər",
            "our services": "Xidmətlərimiz",
            "read_more": "Daha ətraflı",
            "participate_in_auctions": "Hərracda iştirak",
            "service_schedule": "Xidmət qrafiki",
            "your_name_and_surname": "Adınız və soyadınız",
            "contact_info_phone_or_email": "Əlaqə məlumatları (telefon və ya email)",
            "subject": "Başlıq",
            "your_message": "Mesajınız",
            "calculator": "Kalkulyator",
            "auction": "Hərrac",
            "send": "Göndər",
            "phone": "Telefon",
            "email": "Email",
            "dont_empty_this_field": "Dont't empty this field!",
            "social_media": "Sosial media",
            "contact": "Əlaqə",
            "contact_us": "Bizimlə əlaqə",
            "team": "Komanda",
            "blog_details": "Bloq detalları",
            "recent_blogs": "Ən son bloqlar",
            "about_n_faq": "Haqqımızda&MVS",
            "cars": "Maşınlar",
            "shop": "Mağaza",
            "shop_list": "Mağaza siyahısı",
            "gallery": "Gallery",
            "videos": "Videolar",
            "images": "Şəkillər",
            "blog": "Bloq",
            "team_details": "Komanda məlumatları",
            "team_member": "Komanda üzvü",
            "biography": "Bioqrafiya",
            "recent_cars": "Ən son maşınlar",
            "city": "Şəhər",
            "states": "Ştat",
            "port": "Liman",
            "cars_auction_price": "Avtomobilin hərrac qiyməti",
            "auction_company": "Hərrac şirkəti",
            "calculate": "Kalkulyator",
            "search": "Axtar",
            "are_you_a_robot": "Sən robotsan?",

        },
    }
}
