# Generated by Django 4.0.6 on 2023-09-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('TitleAz', models.TextField()),
                ('TitleEn', models.TextField()),
                ('TitleRu', models.TextField()),
                ('ContentAz', models.TextField()),
                ('ContentEn', models.TextField()),
                ('ContentRu', models.TextField()),
                ('Image', models.TextField()),
                ('FooterAz', models.TextField()),
                ('FooterEn', models.TextField()),
                ('FooterRu', models.TextField()),
            ],
            options={
                'db_table': 'About',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Password', models.TextField()),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Username', models.TextField()),
                ('UserImage', models.TextField()),
                ('TitleAz', models.TextField()),
                ('TitleEn', models.TextField()),
                ('TitleRu', models.TextField()),
                ('ContentAz', models.TextField()),
                ('ContentEn', models.TextField()),
                ('ContentRu', models.TextField()),
                ('AddDate', models.DateTimeField()),
                ('Image', models.TextField()),
                ('Count', models.IntegerField()),
                ('ContentHtmlAz', models.TextField()),
                ('ContentHtmlEn', models.TextField()),
                ('ContentHtmlRu', models.TextField()),
            ],
            options={
                'db_table': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProductId', models.IntegerField()),
                ('UserId', models.IntegerField()),
                ('Price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('QuestionAz', models.TextField()),
                ('QuestionEn', models.TextField()),
                ('QuestionRu', models.TextField()),
                ('AnswerAz', models.TextField()),
                ('AnswerEn', models.TextField()),
                ('AnswerRu', models.TextField()),
            ],
            options={
                'db_table': 'Faqs',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Type', models.IntegerField()),
                ('ImagePath', models.TextField()),
                ('VideoLink', models.TextField()),
            ],
            options={
                'db_table': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Subject', models.TextField()),
                ('Content', models.TextField()),
                ('AddDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Content', models.TextField()),
                ('AddDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderNow',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=255, null=True)),
                ('LastName', models.CharField(max_length=255, null=True)),
                ('Phone', models.CharField(max_length=255, null=True)),
                ('Email', models.CharField(max_length=255, null=True)),
                ('Message', models.TextField(null=True)),
                ('LotId', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'OrderNow',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('LogoPath', models.TextField()),
            ],
            options={
                'db_table': 'Partners',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('BrandId', models.IntegerField()),
                ('ModelId', models.IntegerField()),
                ('CurrencyId', models.IntegerField()),
                ('Code', models.TextField()),
                ('NameAz', models.TextField()),
                ('NameEn', models.TextField()),
                ('NameRu', models.TextField()),
                ('Price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('PriceWithSale', models.DecimalField(decimal_places=4, max_digits=18)),
                ('StockCount', models.IntegerField()),
                ('MainImage', models.TextField()),
                ('AboutAz', models.TextField()),
                ('AboutEn', models.TextField()),
                ('AboutRu', models.TextField()),
                ('AddDate', models.DateTimeField()),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ProductId', models.IntegerField()),
                ('ImagePath', models.TextField()),
            ],
            options={
                'db_table': 'ProductImages',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=300)),
                ('City', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Postcode', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Quantity', models.IntegerField()),
                ('Date', models.DateTimeField()),
                ('PaymentStatus', models.IntegerField()),
            ],
            options={
                'db_table': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SaleId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Total', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'SaleProduct',
            },
        ),
        migrations.CreateModel(
            name='ScrapingHistory',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now_add=True)),
                ('TotalLotsScraped', models.BigIntegerField(default=0)),
                ('TotalCrawlPages', models.BigIntegerField(default=0)),
                ('TotalLotsStartedScraping', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'ScrapingHistory',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.TextField()),
                ('NameEn', models.TextField()),
                ('NameRu', models.TextField()),
                ('AboutAz', models.TextField()),
                ('AboutEn', models.TextField()),
                ('AboutRu', models.TextField()),
                ('ImagePath', models.TextField()),
                ('MainImage', models.TextField()),
            ],
            options={
                'db_table': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=300)),
                ('CustomerCount', models.IntegerField()),
                ('CarCount', models.IntegerField()),
                ('AuctionCount', models.IntegerField()),
                ('NameAz', models.TextField()),
                ('NameEn', models.TextField()),
                ('NameRu', models.TextField()),
            ],
            options={
                'db_table': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ImagePath', models.TextField()),
                ('TitleAz', models.TextField(max_length=500)),
                ('TitleEn', models.TextField(max_length=500)),
                ('TitleRu', models.TextField(max_length=500)),
            ],
            options={
                'db_table': 'SliderImages',
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Icon', models.TextField()),
            ],
            options={
                'db_table': 'SocialMedias',
            },
        ),
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('SocialMediaId', models.IntegerField()),
                ('AccountLink', models.TextField()),
            ],
            options={
                'db_table': 'SocialMediaAccounts',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=100)),
                ('Lastname', models.CharField(max_length=100)),
                ('Image', models.TextField()),
                ('Profession', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=100)),
                ('Address', models.TextField(max_length=300)),
                ('Biography', models.TextField()),
            ],
            options={
                'db_table': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='TeamSocialMedia',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('TeamId', models.IntegerField()),
                ('SocialMediaId', models.IntegerField()),
                ('AccountLink', models.TextField()),
                ('Icon', models.TextField()),
            ],
            options={
                'db_table': 'TeamSocialMedias',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('Profession', models.CharField(max_length=100)),
                ('Comment', models.TextField(max_length=500)),
                ('Image', models.TextField()),
                ('AddDate', models.DateTimeField()),
                ('StarCount', models.IntegerField()),
            ],
            options={
                'db_table': 'Testimonials',
            },
        ),
    ]
