# Generated by Django 4.0.6 on 2023-09-27 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myroot', '0001_initial'),
    ]

    operations = [
    ]
