# Generated by Django 4.0.6 on 2023-09-27 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionCompany',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('GateFee', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'AuctionCompanies',
            },
        ),
        migrations.CreateModel(
            name='AuctionFee',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('StartPrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('EndPrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Fee', models.DecimalField(decimal_places=4, max_digits=18)),
                ('AuctionCompanyId', models.BigIntegerField()),
            ],
            options={
                'db_table': 'AuctionFees',
            },
        ),
        migrations.CreateModel(
            name='AuctionOnlinelivebid',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('AuctionCompanyId', models.BigIntegerField()),
                ('StartPrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('EndPrice', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Fee', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'AuctionOnlinelivebids',
            },
        ),
        migrations.CreateModel(
            name='AuctionShipping',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('AuctionCompanyId', models.ForeignKey(db_column='AuctionCompanyId', on_delete=django.db.models.deletion.CASCADE, to='auction.auctioncompany')),
            ],
            options={
                'db_table': 'AuctionShippings',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('Port', models.CharField(max_length=255)),
                ('State', models.CharField(max_length=255)),
                ('Country', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='ShippingAuctionFee',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('AuctionShippingId', models.BigIntegerField()),
                ('UserTypesId', models.BigIntegerField()),
                ('CitiesId', models.BigIntegerField()),
                ('Fee', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'ShippingAuctionFees',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Active', models.IntegerField()),
                ('UserTypesId', models.BigIntegerField()),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserTypes',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Marja', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ServiceFee', models.DecimalField(decimal_places=4, max_digits=18)),
                ('ToBakuFee', models.DecimalField(decimal_places=4, max_digits=18)),
            ],
            options={
                'db_table': 'UserTypes',
            },
        ),
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Chosen', models.IntegerField()),
                ('AuctionShipping', models.ManyToManyField(through='auction.AuctionShipping', to='auction.auctioncompany')),
            ],
            options={
                'db_table': 'ShippingCompanies',
            },
        ),
        migrations.AddField(
            model_name='auctionshipping',
            name='ShippingCompanyId',
            field=models.ForeignKey(db_column='ShippingCompanyId', on_delete=django.db.models.deletion.CASCADE, to='auction.shippingcompany'),
        ),
        migrations.AddField(
            model_name='auctioncompany',
            name='AuctionShipping',
            field=models.ManyToManyField(through='auction.AuctionShipping', to='auction.shippingcompany'),
        ),
    ]
