# Generated by Django 4.0.6 on 2023-09-28 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutoPart',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
            options={
                'db_table': 'AutoPart',
            },
        ),
        migrations.CreateModel(
            name='BanType',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'BanTypes',
            },
        ),
        migrations.CreateModel(
            name='BidInformation',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('LotId', models.BigIntegerField()),
                ('BidStatus', models.TextField(null=True)),
                ('SaleStatus', models.TextField(null=True)),
                ('CurrentBid', models.TextField(null=True)),
                ('Currency', models.TextField(null=True)),
            ],
            options={
                'db_table': 'BidInformation',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('StatusId', models.IntegerField()),
                ('BrandId', models.IntegerField()),
                ('ModelId', models.IntegerField()),
                ('FuelId', models.IntegerField()),
                ('ColorId', models.IntegerField()),
                ('CurrencyId', models.IntegerField()),
                ('BanTypeId', models.IntegerField()),
                ('Distance', models.IntegerField()),
                ('Year', models.IntegerField()),
                ('SpeedBoxId', models.IntegerField()),
                ('EngineCapacity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('MainImage', models.TextField()),
                ('VideoLink', models.TextField()),
                ('Price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('PriceWithSale', models.DecimalField(decimal_places=4, max_digits=18)),
                ('Location', models.CharField(max_length=200)),
                ('Date', models.DateTimeField()),
                ('AboutAz', models.TextField()),
                ('AboutEn', models.TextField()),
                ('AboutRu', models.TextField()),
            ],
            options={
                'db_table': 'Cars',
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('CarId', models.IntegerField()),
                ('MainImage', models.TextField()),
            ],
            options={
                'db_table': 'CarImage',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Colors',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='DamageType',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
                ('Priority', models.IntegerField()),
            ],
            options={
                'db_table': 'DamageType',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Name', models.TextField()),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'db_table': 'Feature',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
                ('CustomsCalculatorId', models.IntegerField(default=None, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Fuel',
                'verbose_name_plural': 'Fuel',
                'db_table': 'Fuel',
            },
        ),
        migrations.CreateModel(
            name='KoreanLotImage',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Korean Lot Image',
                'verbose_name_plural': 'Korean Lot Images',
                'db_table': 'KoreanLotImage',
            },
        ),
        migrations.CreateModel(
            name='LotData',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('lotId', models.BigIntegerField(unique=True)),
                ('year', models.BigIntegerField(null=True)),
                ('make', models.CharField(max_length=255, null=True)),
                ('modelGroup', models.CharField(max_length=255, null=True)),
                ('model', models.CharField(max_length=255, null=True)),
                ('bodyStyle', models.CharField(max_length=255, null=True)),
                ('color', models.CharField(max_length=255, null=True)),
                ('primaryDamage', models.CharField(max_length=255, null=True)),
                ('vin', models.CharField(max_length=255, null=True)),
                ('odometer', models.IntegerField(null=True)),
                ('engineSize', models.CharField(max_length=255, null=True)),
                ('locationName', models.CharField(max_length=255, null=True)),
                ('vehicleType', models.CharField(max_length=255, null=True)),
                ('imageFull', models.CharField(max_length=255, null=True)),
                ('imageThumb', models.CharField(max_length=255, null=True)),
                ('vinHash', models.CharField(max_length=255, null=True)),
                ('saledate', models.DateTimeField(blank=True, null=True)),
                ('searchTerm', models.CharField(max_length=255, null=True)),
                ('dateCreated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('transmission', models.CharField(max_length=255, null=True)),
                ('drive', models.CharField(max_length=255, null=True)),
                ('cylinders', models.TextField(null=True)),
                ('fuel', models.CharField(max_length=255, null=True)),
                ('keys', models.CharField(max_length=255, null=True)),
                ('secondaryDamage', models.CharField(max_length=255, null=True)),
                ('odometerType', models.CharField(max_length=255, null=True)),
                ('auctionCompanyId', models.IntegerField(null=True)),
                ('buyItNow', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'LotData',
            },
        ),
        migrations.CreateModel(
            name='LotImages',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('LotId', models.BigIntegerField()),
                ('ImageFull', models.TextField()),
            ],
            options={
                'db_table': 'LotImages',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
                ('BrandId', models.IntegerField()),
            ],
            options={
                'db_table': 'Models',
            },
        ),
        migrations.CreateModel(
            name='SaleInformation',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('LotId', models.BigIntegerField()),
                ('Lane', models.TextField(null=True)),
                ('Item', models.TextField(null=True)),
                ('Grid', models.TextField(null=True)),
                ('Row', models.TextField(null=True)),
                ('LastUpdated', models.DateTimeField()),
            ],
            options={
                'db_table': 'SaleInformation',
            },
        ),
        migrations.CreateModel(
            name='SpeedBox',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'SpeedBoxes',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('NameAz', models.CharField(max_length=100)),
                ('NameEn', models.CharField(max_length=100)),
                ('NameRu', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='KoreanLot',
            fields=[
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Engine', models.IntegerField()),
                ('Odometer', models.IntegerField()),
                ('Price', models.FloatField()),
                ('NumberOfSeats', models.IntegerField()),
                ('Vin', models.TextField()),
                ('Commnet', models.TextField()),
                ('Drive', models.CharField(choices=[('FWD', 'FWD'), ('RWD', 'RWD'), ('AWD', 'AWD')], max_length=255)),
                ('Transmission', models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=255)),
                ('IsPublished', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=255)),
                ('MainImage', models.ImageField(upload_to='')),
                ('VideoLink', models.TextField()),
                ('Documents', models.FileField(upload_to='')),
                ('BodyStyle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.bantype')),
                ('ChangedParts', models.ManyToManyField(related_name='manual_lots_parts_changed', to='car_details.autopart')),
                ('Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.color')),
                ('Features', models.ManyToManyField(related_name='manual_lots', to='car_details.feature')),
                ('FuelType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.fuel')),
                ('Images', models.ManyToManyField(to='car_details.koreanlotimage')),
                ('Location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.country')),
                ('Make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.brand')),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.model')),
                ('PaintedParts', models.ManyToManyField(related_name='manual_lots_parts_painted', to='car_details.autopart')),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.status')),
            ],
            options={
                'verbose_name': 'Korean Lot',
                'verbose_name_plural': 'Korean Lots',
                'db_table': 'KoreanLot',
            },
        ),
    ]
