# Generated by Django 4.0.6 on 2023-10-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotdata',
            name='lotId',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
