# Generated by Django 4.0.6 on 2023-10-25 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_details', '0002_alter_lotdata_lotid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bidinformation',
            name='LotId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.lotdata'),
        ),
        migrations.AlterField(
            model_name='lotimages',
            name='LotId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.lotdata'),
        ),
        migrations.AlterField(
            model_name='saleinformation',
            name='LotId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_details.lotdata'),
        ),
    ]
