import scrapy


class Auction(scrapy.Item):
    LotId = scrapy.Field()
    Year = scrapy.Field()
    Make = scrapy.Field()
    ModelGroup = scrapy.Field()
    Model = scrapy.Field()
    BodyStyle = scrapy.Field()
    Color = scrapy.Field()
    PrimaryDamage = scrapy.Field()
    Vin = scrapy.Field()
    Odometer = scrapy.Field()
    EngineSize = scrapy.Field()
    LocationName = scrapy.Field()
    VehicleType = scrapy.Field()
    ImageFull = scrapy.Field()
    ImageThumb = scrapy.Field()
    VinHash = scrapy.Field()
    SaleDate = scrapy.Field()
    SearchTerm = scrapy.Field()
    DateCreated = scrapy.Field()
    OdometerType = scrapy.Field()
    Currency = scrapy.Field()
    Images = scrapy.Field()
    Grid = scrapy.Field()
    Row = scrapy.Field()
    Lane = scrapy.Field()
    Item = scrapy.Field()
    LastUpdated = scrapy.Field()
    SaleStatus = scrapy.Field()
    BidStatus = scrapy.Field()
    CurrentBid = scrapy.Field()
    Transmission = scrapy.Field()
    Drive = scrapy.Field()
    Cylinders = scrapy.Field()
    Fuel = scrapy.Field()
    Keys = scrapy.Field()
    SecondaryDamage = scrapy.Field()
    AuctionCompanyId = scrapy.Field()
    BuyItNow = scrapy.Field()
